// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
)

type Querier interface {
	CreateItem(ctx context.Context, item string) (Item, error)
	GetItem(ctx context.Context, id int64) (Item, error)
	GetItemForUpdate(ctx context.Context, id int64) (Item, error)
	ListItem(ctx context.Context, arg ListItemParams) ([]Item, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error)
}

var _ Querier = (*Queries)(nil)
